<!--########################################## -->
<!-- section politicas y tratamiento de datos personales -->
<section class="politicaPrivacidad">
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-10  margen-superior text-center wow zoomIn" data-wow-delay="0.4s">
                <h1 class="h1-responsive ">Política de Privacidad y Tratamiento de los Datos Personales </h1>
            </div>
            <div class="col-12 text-center">
                <p class="text-justify mt-3 wow fadeInLeft" data-wow-delay="0.4s">
                Su privacidad y confianza son muy importantes para nosotros. Por ello, queremos asegurarnos que conozca cómo 
                salvaguardamos la integridad, confidencialidad y disponibilidad, de 
                sus datos personales, en apego a la legislación colombiana.
                </p>
                <p class="text-justify mt-3 wow fadeInLeft" data-wow-delay="0.4s">
                En cumplimiento al Artículo 10 del Decreto 1377 de 2013, solicitamos su autorización para continuar con el 
                tratamiento de sus datos personales con el fin de recolectar, recaudar, almacenar, usar, circular, suprimir, procesar, compilar, intercambiar, dar tratamiento, actualizar, disponer de los datos personales que usted nos ha suministrado
                 y que han sido incorporados en las bases de datos con las que cuenta ARRAY. 
                </p>
                <p class="text-justify mt-3 wow fadeInLeft" data-wow-delay="0.4s">
                Así mismo usted podrá ejercer los derechos de conocer, actualizar, rectificar, suprimir, solicitar 
                prueba de la autorización, ser informado del uso de sus datos personales, presentar ante la Superintendencia de Industria y Comercio quejas por infracciones a los dispuesto en la presente ley y las demás normas que la modifiquen, adicionen o complementen, para cualquier inquietud al respecto ponemos a su disposición el correo electrónico contacto@array.com.co o sientase cómodo hablando con "Sair", el cual es un chat que encuentra en la parte inferior de este sitio, 
                donde podrá éxponer sus inquietudes e interactuar con nuestros asesores de manera Sincrónica.
                </p>
                <p class="text-justify mt-3 wow fadeInLeft" data-wow-delay="0.4s">
                Este documento contempla nuestra política de protección y tratamiento de los datos personales la cual tiene 
                como fin informar cuáles datos son capturados en la prestación de nuestros servicios y productos y para cuales finalidades, cuando la compartimos, como la usamos y protegemos, como también los derechos que le asisten a los titulares de los datos personales y como ejercerlos. La información y/o datos personales que 
                recolectamos de usted que es nuestro cliente, son los siguientes:
                <h3 class="text-left wow fadeInLeft" data-wow-delay="0.4s">Datos para ser usuario ARRAY</h3>
                <div class="text-left pl-2 wow fadeInLeft" data-wow-delay="0.4s">
                
                    <li>Nombres</li>
                    <li>Apellidos</li>
                    <li>Correo Electónico.</li>
                </div>
                <p class="text-justify mt-2 wow fadeInLeft" data-wow-delay="0.4s">Estos datos son necesarios para que nuestros nuevos clientes tengan acceso a la plataforma ARRAY como miembros. 
                    Los Nombres y apellidos nos facilitan conocer con quien estamos tratando, además usted como usuario necesita estar identificado dentro de la plataforma. 
                    Por lo anterior es de vital importancia que al momento de registrarse usted también suministre una contraseña, para que su información y 
                    actividades con nosotros queden en privado y de forma segura.
                </p>
                <h3 class="text-left wow fadeInLeft" data-wow-delay="0.4s">Datos para comprar nuestros productos de contado</h3>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <h3 class="text-left wow fadeInLeft" data-wow-delay="0.4s">Datos para comprar nuestros productos con financiación</h3>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <h3 class="text-left wow fadeInLeft" data-wow-delay="0.4s">Datos para contratar nuestros servicios de contado</h3>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <h3 class="text-left wow fadeInLeft" data-wow-delay="0.4s">Datos para contratar nuestros servicios con financiación</h3>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <h3 class="text-left wow fadeInLeft" data-wow-delay="0.4s">Datos Volátiles</h3>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
                <P class="text-left wow fadeInLeft" data-wow-delay="0.4s">.......................................
                .....................................................................................................................................................................................
                ......................................................................</P>
            </div>
        </div>
    </div>
</section>
<!--Fin section politicas y tratamiento de datos personales-->
<!-- ########################################## -->


